AWSTemplateFormatVersion: '2010-09-09'
Description: 'DynamoDB table for FireBot coordination'

Resources:
  FireBotFunction:
    Type: 'AWS::Lambda::Function'
    Properties:
      FunctionName: firebot-handler
      Runtime: python3.11
      Handler: lambda_function.lambda_handler
      Code:
        S3Bucket: !Ref 'CodeBucket'
        S3Key: !Ref 'CodeKey'
      Role: !GetAtt LambdaExecutionRole.Arn
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          DYNAMODB_TABLE_NAME: !Ref FireBotCoordinationTable
          AWS_REGION: !Ref 'AWS::Region'

  FireBotCoordinationTable:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: firebot-coordination
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: incident_key
          AttributeType: S
      KeySchema:
        - AttributeName: incident_key
          KeyType: HASH
      TimeToLiveSpecification:
        AttributeName: expiration_time
        Enabled: true

  LambdaExecutionRole:
    Type: 'AWS::IAM::Role'
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
      Policies:
        - PolicyName: DynamoDBAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - dynamodb:PutItem
                  - dynamodb:GetItem
                  - dynamodb:DeleteItem
                  - dynamodb:UpdateItem
                  - dynamodb:Query
                Resource: !GetAtt FireBotCoordinationTable.Arn

Parameters:
  CodeBucket:
    Type: String
    Description: S3 bucket containing the Lambda function code
  CodeKey:
    Type: String
    Description: S3 key for the Lambda function code

Outputs:
  TableName:
    Description: Name of the DynamoDB table
    Value: !Ref FireBotCoordinationTable
  TableArn:
    Description: ARN of the DynamoDB table
    Value: !GetAtt FireBotCoordinationTable.Arn 