name: Build Lambda Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Clear pip cache
        run: rm -rf ~/.cache/pip

      - name: Install clean dependencies and package Lambda
        run: |
          rm -rf package/ lambda_package.zip
          pip install --upgrade pip
          pip install -r requirements.txt -t package/
          cp lambda_function.py package/
          
      - name: Create Lambda package zip
        run: |
          # Remove any existing zip
          rm -f lambda_package.zip
          
          # Use Python to create a proper Lambda zip with files at root level
          python3 << 'EOF'
          import zipfile
          import os
          import fnmatch
          
          def should_exclude(filepath):
              exclude_patterns = ['*.pyc', '*/__pycache__/*', '*.pyo', '*/.DS_Store', '*.egg-info/*']
              for pattern in exclude_patterns:
                  if fnmatch.fnmatch(filepath, pattern):
                      return True
              return False
          
          with zipfile.ZipFile('lambda_package.zip', 'w', zipfile.ZIP_DEFLATED) as zipf:
              # Walk through the package directory
              for root, dirs, files in os.walk('package'):
                  # Remove __pycache__ from dirs to avoid traversing
                  dirs[:] = [d for d in dirs if d != '__pycache__']
                  
                  for file in files:
                      filepath = os.path.join(root, file)
                      # Calculate the archive path (remove 'package/' prefix)
                      arcname = os.path.relpath(filepath, 'package')
                      
                      # Skip excluded files
                      if not should_exclude(filepath):
                          print(f"Adding: {arcname}")
                          zipf.write(filepath, arcname)
          
          print("Lambda package created successfully!")
          EOF
          
      - name: Verify package contents
        run: |
          echo "=== Lambda package file info ==="
          ls -lh lambda_package.zip
          echo ""
          echo "=== Lambda package contents (first 30 entries) ==="
          unzip -l lambda_package.zip | head -30
          echo ""
          echo "=== Checking for lambda_function.py at root ==="
          if unzip -l lambda_package.zip | grep -E "^[[:space:]]*[0-9]+[[:space:]]+[0-9-]+[[:space:]]+[0-9:]+[[:space:]]+lambda_function\.py$"; then
            echo "✅ lambda_function.py found at root level"
          else
            echo "❌ ERROR: lambda_function.py not found at root level"
            echo "Full zip listing:"
            unzip -l lambda_package.zip
          fi
          echo ""
          echo "=== Testing unzip to temp directory ==="
          mkdir -p temp_test
          cd temp_test
          unzip -q ../lambda_package.zip
          echo "Contents after unzip:"
          ls -la
          if [ -f "lambda_function.py" ]; then
            echo "✅ lambda_function.py exists at root after unzip"
          else
            echo "❌ lambda_function.py missing at root after unzip"
            find . -name "lambda_function.py" -type f
          fi
          cd ..
          rm -rf temp_test

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-package
          path: lambda_package.zip
