name: Build Lambda Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Lambda package in Docker
        run: |
          docker run --rm -v "$PWD:/app" -w /app python:3.11-slim bash -c "
            pip install --upgrade pip &&
            pip install --no-cache-dir -r requirements.txt -t python &&
            cp lambda_function.py python &&
            cd python && zip -r ../lambda_package.zip .
          "

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-package
          path: lambda_package.zip
