name: Build Lambda Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install zip (required for packaging)
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Clear Python cache
        run: |
          rm -rf ~/.cache/pip
          
      - name: Install dependencies into build dir
        run: |
          pip install --upgrade pip
          pip install -r requirements.txt -t python/
          cp lambda_function.py python/
          cd python && zip -r ../lambda_package.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-package
          path: lambda_package.zip
