name: Build Lambda Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Clear pip cache (optional but helps avoid stale builds)
        run: rm -rf ~/.cache/pip

    - name: Force upgrade Gemini and package Lambda
        run: |
            pip install --upgrade --force-reinstall google-generativeai==0.5.2
            pip install -r requirements.txt -t package/
            pip install --upgrade --force-reinstall google-generativeai==0.5.2 -t package/
            cp lambda_function.py package/
            cd package && zip -r ../lambda_package.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-package
          path: lambda_package.zip
