name: Build Lambda Package

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install zip
        run: sudo apt-get update && sudo apt-get install -y zip

      - name: Clear pip cache
        run: rm -rf ~/.cache/pip

      - name: Install clean dependencies and package Lambda
        run: |
          rm -rf package/ lambda_package.zip
          pip install --upgrade pip
          pip install -r requirements.txt -t package/
          cp lambda_function.py package/
          
      - name: Create Lambda package zip
        run: |
          cd package
          zip -r ../lambda_package.zip . -x "*.pyc" "*/__pycache__/*"
          cd ..
          
      - name: Verify package contents
        run: |
          echo "=== Lambda package contents ==="
          unzip -l lambda_package.zip | head -20
          echo "=== Checking for lambda_function.py at root ==="
          unzip -l lambda_package.zip | grep "lambda_function.py" || echo "ERROR: lambda_function.py not found at root level"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-package
          path: lambda_package.zip
